---
platform: linux
image: docker:///pivotalgreenhouse/ruby
inputs:
  - name: diego-windows-msi
  - name: msi-file
  - name: diego-release
  - name: cf-release
  - name: cf-diego-dwm-locker
run:
  path: diego-windows-msi/scripts/commit-shas-to-git.sh
params:
  GITHUB_TOKEN:
