---
platform: linux
image: docker:///pivotalgreenhouse/ruby
inputs:
  - name: diego-windows-msi
  - name: msi-file
run:
  path: diego-windows-msi/scripts/release.rb
params:
  BOSH_TARGET:
  BOSH_PASSWORD:
  BOSH_USER:
  GITHUB_TOKEN:
  
