---
platform: linux
image: docker:///golang#1.4
inputs:
  - name: diego-windows-msi
run:
  path: diego-windows-msi/src/github.com/pivotal-cf-experimental/nora/scripts/run_wats.sh
params:
  ADMIN_PASSWORD:
  ADMIN_USER:
  API:
  APPS_DOMAIN:
  DOPPLER_URL:
  SOCKET_ADDRESS_FOR_SECURITY_GROUP_TEST:
